In [ ]:
Each row represents one intern.

Each column represents a feature.

Input features: Task_Completion, Consistency, Engagement.

Target variable: Performance (Poor, Average, Good, Excellent).

Problem Type: Multi-class Classification.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
df = pd.read_csv("intern_performance_500_with_ID.csv")
df.head()

  Intern_ID  Task_Completion  Consistency  Engagement Performance
0    INT001             69.0          NaN        87.0        Good
1    INT002             95.0         90.0        62.0        Good
2    INT003             63.0         92.0        92.0        Good
3    INT004             73.0         41.0        70.0     Average
4    INT005             95.0         73.0        95.0        Good

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Intern_ID        500 non-null    object
 1   Task_Completion  494 non-null    float64
 2   Consistency      491 non-null    float64
 3   Engagement       495 non-null    float64
 4   Performance      500 non-null    object
dtypes: float64(3), object(2)
memory usage: 19.7+ KB

In [11]:
df.isnull().sum()

Intern_ID          0
Task_Completion    6
Consistency        9
Engagement         5
Performance        0
dtype: int64

In [12]:
df.fillna(df.mean(numeric_only=True), inplace=True)

In [13]:
df.isnull().sum()

Intern_ID          0
Task_Completion    0
Consistency        0
Engagement         0
Performance        0
dtype: int64

In [15]:
df = pd.concat([df, df.iloc[[0]]])

df.to_csv("intern_performance_500_with_ID.csv", index=False)

In [16]:
df.duplicated().sum()

np.int64(2)

In [17]:
df.drop_duplicates(inplace=True)

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.to_csv("cleaned_intern_data.csv", index=False)

In [20]:
df.describe()

       Task_Completion  Consistency  Engagement
count       500.000000   500.000000  500.000000
mean         69.623482    68.977597   69.654545
std          17.813775    17.396747   17.686421
min          40.000000    40.000000   40.000000
25%          54.000000    53.750000   54.000000
50%          69.000000    68.977597   70.000000
75%          85.000000    83.000000   85.000000
max         100.000000   100.000000  100.000000