In [1]:
import pandas as pd
import numpy as np

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
df = pd.read_csv("intern_performance_real.csv")

df.head()

  Intern_ID  Completion_Time  Feedback_Rating  Attendance  Performance_Score
0   INT0001             3.26             4.09       86.50              70.98
1   INT0002              NaN             1.33       59.23              42.16
2   INT0003             5.78              NaN       42.98              49.89
3   INT0004             4.28             1.43       83.16              68.49
4   INT0005             1.53             1.91       74.10              77.51

In [3]:
df = df.drop("Intern_ID", axis=1)

df = df.fillna(df.mean())

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Completion_Time    10000 non-null  float64
 1   Feedback_Rating    10000 non-null  float64
 2   Attendance         10000 non-null  float64
 3   Performance_Score  10000 non-null  float64
dtypes: float64(4)
memory usage: 312.6 KB

In [4]:
# Fix zero attendance
df["Attendance"] = df["Attendance"].replace(0, 1)

# Feature Engineering
df["Work_Efficiency"] = df["Completion_Time"] / df["Attendance"]

df["Engagement_Score"] = df["Feedback_Rating"] * df["Attendance"]

df["Productivity"] = df["Completion_Time"] * df["Feedback_Rating"]

df["Feedback_Impact"] = df["Feedback_Rating"] ** 2

In [5]:
df.head()

,Completion_Time,Feedback_Rating,Attendance,Performance_Score,Work_Efficiency,Engagement_Score,Productivity,Feedback_Impact
0,3.260000,4.090000,86.50,70.98,0.037688,353.785000,13.333400,16.728100
1,3.958567,1.330000,59.23,42.16,0.066834,78.775900,5.264894,1.768900
2,5.780000,2.909313,42.98,49.89,0.134481,125.042276,16.815830,8.464103
3,4.280000,1.430000,83.16,68.49,0.051467,118.918800,6.120400,2.044900
4,1.530000,1.910000,74.10,77.51,0.020648,141.531000,2.922300,3.648100